# Define os serviços (containers) que compõem a aplicação
services:
    # Serviço da aplicação Laravel com PHP-FPM
    app:
        # Configuração de build da imagem personalizada
        build:
            args:
                user: user-docker # Nome do usuário no container
                uid: 1000 # UID do usuário do host (deve corresponder ao seu UID)
            context: ./ # Diretório onde está o Dockerfile
            dockerfile: Dockerfile # Nome do arquivo Dockerfile
        image: starter-pack-app # Nome da imagem Docker gerada
        container_name: starter-pack-api # Nome do container
        restart: unless-stopped # Reinicia automaticamente (exceto se parado manualmente)
        working_dir: /var/www/ # Diretório de trabalho dentro do container
        user: "1000:1000" # Executa como usuário/grupo com UID 1000
        environment:
            - XDEBUG_MODE=debug
            - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 idekey=docker
        # Volumes - monta diretórios/arquivos do host no container
        volumes:
            - ./:/var/www # Monta código fonte do projeto no container
            - ./docker/php/php-local.ini:/usr/local/etc/php/conf.d/php-local.ini # Configurações PHP personalizadas
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # Configurações Xdebug personalizadas
        # Rede customizada para comunicação entre containers
        networks:
            - starter-pack

    # Serviço do nginx para servir a aplicação
    nginx:
        image: nginx:alpine
        container_name: starter-pack-nginx
        restart: unless-stopped
        ports:
            - 9080:80 # Acessa aplicação em http://localhost:9080
        volumes:
            - ./:/var/www # Monta código fonte do projeto no container
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # Configuração do nginx
        depends_on:
            - app
        networks:
            - starter-pack

# Define redes customizadas para comunicação entre containers
networks:
    starter-pack: # Nome da rede
        driver: bridge # Driver de rede (padrão para containers na mesma máquina)
